name: lesson1
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  build_runner: ^2.3.3
  dio: ^5.0.1
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1