name: flutter_parse_n_list
description: Parsing and Viewing list
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  build_runner: ^2.3.3
  dio: ^5.0.3
  json_annotation: ^4.8.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true