name: lesson2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1dart

environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies:
  build_runner: ^2.3.3
  dio: ^5.0.1
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  flutter_bloc: ^8.1.2
  bloc: ^8.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

